### ISSUE TITLE
Compatibility Symfony 3 / Sonata

### ISSUE THREAD

**Issue by jeroendk** [nan-guo/Sonata-Menu-Bundle#1]
Hi!

First of all, great bundle! 

I was trying it out in a Symfony 3.4 project with the newest Sonata Admin bundle and found some bugs related to these versions I think. Would love to create a pull request to fix it but I wonder if you need the Symfony 2.8 compatibility ? Since your bundle has just been released.

**Comment by nan-guo** [comment]
Thinks for your attention. Not necessarily compatible with 2.8, this bundle will focus on version 3.x in the furture, you are welcome to improve some bug.

**Comment by jeroendk** [comment]
Allright check out my Pull request: #2

**Comment by nan-guo** [comment]
Think you very much.
