### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by deyvid5** [nan-guo/Sonata-Menu-Bundle#11]
I have problem with routes on Symfony4.
Everything configured as you've written.

Having this kind of error:
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_sonata_menu_menu_create" as such route does not exist.").

What is strange, I could notice some similar routes but not quite the same:
My router:debug returns:

admin_app_menu_list                             ANY              ANY      ANY    /admin/sonata/menu/list
  admin_app_menu_create                           ANY              ANY      ANY    /admin/sonata/menu/create
  admin_app_menu_batch                            ANY              ANY      ANY    /admin/sonata/menu/batch
  admin_app_menu_edit                             ANY              ANY      ANY    /admin/sonata/menu/{id}/edit
  admin_app_menu_delete                           ANY              ANY      ANY    /admin/sonata/menu/{id}/delete
  admin_app_menu_show                             ANY              ANY      ANY    /admin/sonata/menu/{id}/show
  admin_app_menu_export                           ANY              ANY      ANY    /admin/sonata/menu/export
  admin_app_menu_menuitem_list                    ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/list
  admin_app_menu_menuitem_create                  ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/create
  admin_app_menu_menuitem_batch                   ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/batch
  admin_app_menu_menuitem_edit                    ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/{childId}/edit
  admin_app_menu_menuitem_delete                  ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/{childId}/delete
  admin_app_menu_menuitem_show                    ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/{childId}/show
  admin_app_menu_menuitem_export                  ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/export
  admin_app_menu_menuitem_toggle                  ANY              ANY      ANY    /admin/sonata/menu/{id}/sonata/menu/menu-item/{childId}/toggle
  admin_app_menu_items                            ANY              ANY      ANY    /admin/sonata/menu/{id}/items
  admin_app_menuitem_list                         ANY              ANY      ANY    /admin/sonata/menu/menu-item/list
  admin_app_menuitem_create                       ANY              ANY      ANY    /admin/sonata/menu/menu-item/create
  admin_app_menuitem_batch                        ANY              ANY      ANY    /admin/sonata/menu/menu-item/batch
  admin_app_menuitem_edit                         ANY              ANY      ANY    /admin/sonata/menu/menu-item/{id}/edit
  admin_app_menuitem_delete                       ANY              ANY      ANY    /admin/sonata/menu/menu-item/{id}/delete
  admin_app_menuitem_show                         ANY              ANY      ANY    /admin/sonata/menu/menu-item/{id}/show
  admin_app_menuitem_export                       ANY              ANY      ANY    /admin/sonata/menu/menu-item/export
  admin_app_menuitem_toggle

Which is quite different regarding the error.

**Comment by nan-guo** [comment]
Hello @deyvid5,

you can find the answer here:
https://sonata-project.org/bundles/admin/3-x/doc/reference/routing.html

If no baseRouteName is defined then the Admin will generate one for you, based on the following format: ‘admin_vendor_bundlename_entityname’ so you will have route names for your actions like ‘admin_vendor_bundlename_entityname_list’.
