### ISSUE TITLE
Can I show this menu in main menu tree ?

### ISSUE THREAD

**Issue by grekpg** [nan-guo/Sonata-Menu-Bundle#16]
I create menu is nice. 
But how use it ? Is possible to show in sonata main menu tree ? 
![image](https://user-images.githubusercontent.com/2538271/75961576-8ec28300-5ec2-11ea-85ee-560bbf0c83a4.png)
Here is my menu. Where i can show it ?

**Comment by nan-guo** [comment]
Hello,
After creating your menu, you cloud show it in your twig template or expose your menu data through your API. Here is the doc
https://github.com/nan-guo/Sonata-Menu-Bundle#and-then-its-your-showtime-for-the-frontend-you-can-output-the-results-as-you-want
