### ISSUE TITLE
Change EntityManager in MenuManager.php

### ISSUE THREAD

**Issue by NicolasDW** [nan-guo/Sonata-Menu-Bundle#17]
Hi !

First, great bundle, it's very useful !

You may change the service called in the construct of the class Manager/MenuManager.php to avoid issue with recents versions of Symfony :

`public function __construct(EntityManager $em)`
to
`public function __construct(EntityManagerInterface $em)`

Thanks

**Comment by nan-guo** [comment]
Hi,
thanks for your recommendation, does It looks good for you ?
https://github.com/nan-guo/Sonata-Menu-Bundle/pull/18

**Comment by NicolasDW** [comment]
Hi,

Perfect, thanks !
