### ISSUE TITLE
when delete childen item entity delete parent and all other childens.

### ISSUE THREAD

**Issue by DILL44** [nan-guo/Sonata-Menu-Bundle#9]
the relation entity parent is cascade remove and childen cascade on all 
https://github.com/nan-guo/Sonata-Menu-Bundle/blob/06d4b0fdb687f38f2b3ab716b95fd778b81eedc1/Model/MenuItem.php#L70
https://github.com/nan-guo/Sonata-Menu-Bundle/blob/06d4b0fdb687f38f2b3ab716b95fd778b81eedc1/Model/MenuItem.php#L78
so when you delete a children, model delete parent and all parent's childrens

**Comment by nan-guo** [comment]
PR merged, thx
